name: celeryviz_demo
description: A demo app for the CeleryViz frontend.
publish_to: 'none'
version: 0.0.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  celeryviz_frontend_core:
    git:
      url: https://github.com/bhavya-tech/celeryviz_frontend_core.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/recording.ndjson